### ISSUE TITLE
[Question]  Why is an installation needed ? Why not just copy paste the javascript code ?

### ISSUE THREAD

**Issue by userrand** [b0o/surfingkeys-conf#75]
- Surfingkeys Version:
- Surfingkeys-conf Version (git hash):
- Operating System:
- Browser Version:

## Details

This project looks awesome. I recently discovered SurfingKeys from ChatGPT and feel like I have uncovered an awesome corner of web browsing. This project looks like it adds a lot of neat features which would make it even more awesome. 

However,

Copy pasted from title :

> Why is an installation needed? Why not just copy-paste the code into the settings directly?

My apologies if this was already asked. I searched for the words "install" and did not see anything relevant to my question.

Also, would you happen to know how one may change the search results in visual mode from yellow to some other color?

**Comment by b0o** [comment]
Hi there! 

Good question. The reason it’s not as simple as copy-pasting the script is that this project is broken into multiple files and has a few NPM dependencies. It’s necessary to bundle everything together into a single JavaScript file before it can be added to SurfingKeys.

I do plan to offer a pre-built version that can be copy-pasted or loaded by URL, but I haven’t gotten around to doing that.

In case it’s helpful, I can explain the [instructions in the README](https://github.com/b0o/surfingkeys-conf#installation) to clarify what they are doing:

- the `git clone` step downloads the source code to your computer
- the `npm install` step downloads the dependencies from NPM needed to build the project
- the `npm run gulp install` step is optional, you can either run `npm run gulp install` or `npm run gulp build`.
  - the `gulp build` command is what actually builds the bundle, and it will place it at `./build/surfingkeys.js`. You could then copy and paste the contents of this file into SurfingKeys
  - the `gulp install` does the same thing as `gulp build`, but it also copies the `./build/surfingkeys.js` file to `~/.surfingkeys.js`. If you use Chrome, you can configure Surfingkeys to automatically load your configuration from this file on disk instead of manually copy-pasting

---

For changing the hint color from yellow to another color, here is the default style of the hint from the Surfingkeys [source](https://github.com/brookhong/Surfingkeys/blob/master/src/content_scripts/ui/frontend.css):

```css
div.sk_tab_hint {
    display: inline-block;
    float:right;
    font-size: 10pt;
    font-weight: bold;
    padding: 0px 2px 0px 2px;
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFF785), color-stop(100%,#FFC542));
    color: #000;
    border: solid 1px #C38A22;
    border-radius: 3px;
    box-shadow: 0px 3px 7px 0px rgba(0, 0, 0, 0.3);
}
```

You can adjust the background gradient colors or make it a solid color. To apply your modifications, put them in [`./src/theme.js`](https://github.com/b0o/surfingkeys-conf/blob/main/src/theme.js) and re-build the project.

---

Hope that helps clear things up, let me know if you have any other questions.
